# Generated by Django 3.0.3 on 2020-09-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(blank=True, default='C:\\Users\\User\\Desktop\\Git\\Django\\Confectionary\\mediaclient_default.jpg', upload_to='C:\\Users\\User\\Desktop\\Git\\Django\\Confectionary\\media/ClientAvatars', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='fixedpicture',
            name='picture',
            field=models.ImageField(blank=True, default='C:\\Users\\User\\Desktop\\Git\\Django\\Confectionary\\mediapicture_default.jpg', upload_to='C:\\Users\\User\\Desktop\\Git\\Django\\Confectionary\\media/RecipePictures', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='avatar',
            field=models.ImageField(blank=True, default='C:\\Users\\User\\Desktop\\Git\\Django\\Confectionary\\mediarecipe_default.jpg', upload_to='C:\\Users\\User\\Desktop\\Git\\Django\\Confectionary\\media/RecipeAvatars', verbose_name='Аватарка'),
        ),
    ]
